spring.application.name=atlantidastore
server.port=8080
# ========================
# JPA / Hibernate Configuration
# ========================
# SQLite Database URL - criará atlantidastore.db na pasta do projeto
spring.datasource.url=jdbc:sqlite:atlantidastore.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

app.storage.games-root=data/game-files
app.storage.games-max-size-bytes=524288000
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

app.admin.enabled=true
app.admin.nome=Administrador
app.admin.email=admin@atlantida.local
app.admin.password=admin123
