spring.application.name=atlantidastore
server.port=8081
# ========================
# JPA / Hibernate Configuration
# ========================
# SQLite Database URL - criará atlantidastore.db na pasta do projeto
spring.datasource.url=jdbc:sqlite:atlantidastore.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

